name: Swift
favicon: null
layout_spectrum: 0.73474
typography_spectrum: 0.95613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00abad'
    - '#959597'
    - '#4c4c4c'
  brandStrength: 1
  lightness: 0.8998363274149597
  saturation: 0.6572672561742365
  rhythmicContrast: 0.3095097276382148
purpose: []
